name: Taikon
version: '${project.version}'
main: svend.taikon.Taikon
api-version: '1.17'

depend: [ProtocolLib]
softdepend: [WorldEdit]

commands:
  spawn:
    description: "Телепорт на спавн"

  menu:
    description: "Можно открыть любое меню"

  localBan:
    description: "Забанить игроков с указанным сроком и причиной"

  bust:
    description: "Test busta"

  testReg:
    description: "Ворлд эдит"

#отключение достижений
advancements:
  disable-saving: true
  disabled:
    - '*'

permissions:
  permissions.Permissions:
    default: op